/// Flutter icons SolvedDashboardIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SolvedDashboardIcons
///      fonts:
///       - asset: fonts/SolvedDashboardIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SolvedDashboardIcons {
  SolvedDashboardIcons._();

  static const _kFontFam = 'SolvedDashboardIcons';
  static const String? _kFontPkg = null;

  static const IconData frame_238 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_239 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_240 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_241 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_242 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_243 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_244 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_245 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
